/**
 * DataHuBI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Area } from './area';
import { CampoIndicativo } from './campoIndicativo';


export interface Indicativo { 
    id?: string | null;
    nome?: string | null;
    areaId?: string | null;
    area?: Area;
    campos?: Array<CampoIndicativo> | null;
}

